### ISSUE TITLE
Create a detail page product

### ISSUE THREAD

**Issue by joshvoll** [4piso/kraken-website#3]
As a developer i want to be able to click the link product and display the product detail

**Comment by joshvoll** [comment]
There is a problem on the product detail object, need help for this

**Comment by pipa** [comment]
@joshvoll , what is the problem?

**Comment by joshvoll** [comment]
@luismatute Please provide a different way to for parsing the data, here is how it look right now

[ { _id: '56cf5d3298d8fb6418841ec1',
       service_id: '56cf36d1bd1f52e116fc95cd',
       name: 'Lavado Exterior',
       discount: 0,
       __v: 0,
       date_created: '2016-02-25T19:59:46.851Z',
       requires: [] } ] }

so we need to specify the index in the array before sending it to the front end
